const LANGUAGE_TO_COUNTRY: Record<string, string> = {
  ar: "sa",
  bg: "bg",
  bn: "bd",
  ca: "es",
  cs: "cz",
  da: "dk",
  de: "de",
  el: "gr",
  en: "us",
  eo: "eu",
  es: "es",
  et: "ee",
  fa: "ir",
  fi: "fi",
  fr: "fr",
  ga: "ie",
  gu: "in",
  he: "il",
  hi: "in",
  hr: "hr",
  hu: "hu",
  id: "id",
  it: "it",
  ja: "jp",
  ko: "kr",
  lt: "lt",
  lv: "lv",
  mr: "in",
  ms: "my",
  nl: "nl",
  no: "no",
  pl: "pl",
  pt: "br",
  ro: "ro",
  ru: "ru",
  sk: "sk",
  sl: "si",
  sv: "se",
  sw: "tz",
  ta: "in",
  te: "in",
  th: "th",
  tr: "tr",
  uk: "ua",
  ur: "pk",
  vi: "vn",
  zh: "cn",
};

export const getLanguageFlagCode = (languageCode: string) =>
  LANGUAGE_TO_COUNTRY[languageCode.toLowerCase()] ?? null;
